[project]
name = "jot"
version = "0.1.0"
description = ""
authors = [
    {name = "Colin Putney", email = "colin.putney@descarteslabs.com"},
]
dependencies = [
    "requests~=2.26",
]
requires-python = ">=3.6"
license = {text = "MIT"}

[project.urls]
homepage = ""

[project.optional-dependencies]
[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "pytest~=6.2",
    "pytest-mock~=3.6",
    "mock~=4.0",
    "requests-mock~=1.9.3",
    "tox-pdm~=0.3.1",
]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool.pytest.ini_options]
mock_use_standalone_module = true

[tool.black]
line-length = 100
